name: Sync to Hugging Face hub

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: ActionsDesk/lfs-warning@v2.0
        with:
          filesizelimit: 900000 # so we can sync to HF spaces
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: ls ./**
