# This is a basic workflow to help you get started with Actions

name: max-file-size

uses: ActionsDesk/lfs-warning

with:
  filesizelimit: 900000  # so we can sync with HF spaces

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
